---
- name: Define java_packages.
  set_fact:
    java_packages: "{{ openjdk_packages | list }}"
  when: openjdk_packages is not defined

- name: Installs openjdk Java.
  package: "name={{ item }} state=installed"
  with_items: "{{ openjdk_packages }}"
  when: not install_oracle_java

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'setup-{{ ansible_os_family }}.yml'
    - not-supported.yml
  loop_control:
    loop_var: platform
