---
- name: Define java_packages.
  set_fact:
    java_packages: "{{ openjdk_packages | list }}"
  when: openjdk_packages is not defined

- name: Installs openjdk Java.
  package: "name={{ item }} state=installed"
  with_items: "{{ openjdk_packages }}"
  when: not install_oracle_java

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Debian'
