---

- name: Include version-specific variables for CetnOS.
  include_vars: "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"

- name: Downloads oracle Java
  get_url:
    url:     "{{ urls[java_version] }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ download_dir }}/{{ download_file }}"
  when: install_oracle_java

- name: Installs oracle Java
  yum:
    name: "{{ download_dir }}/{{ download_file }}"
    state: present
  when: install_oracle_java