---
- name: Install WebUpd8 Team Java PPA (for Oracle Java)
  apt_repository: repo={{ java_ppa }} state=present
  when: install_oracle_java
  register: webupd8ppa
  until: webupd8ppa|success
  retries: 5
  delay: 10

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  apt:
    name: "{{ deb_package_name }}"
    state: present
    update_cache: "yes"
