---

- name: Include version-specific variables for CetnOS.
  include_vars: "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"  

- name: Debugging run
  debug:
    msg: "This is {{ java.jre_rpm_url }}"

- name: Downloads oracle Java
  get_url:
    url:     "{{ java.jre_rpm_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java.download_path }}/{{ java.rpm_filename }}.rpm"
  when: install_oracle_java

- name: Installs oracle Java
  yum:
    name: "{{ java.download_path }}/{{ java.rpm_filename }}.rpm"
    state: present
  when: install_oracle_java